/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.osql.parser;

public interface ParserConstants {

  int EOF = 0;
  int LP = 6;
  int RP = 7;
  int NOT = 8;
  int AND = 9;
  int OR = 10;
  int SMALLEROREQ = 11;
  int BIGGEROREQ = 12;
  int NOTEQUAL = 13;
  int EQUAL = 14;
  int SMALLER = 15;
  int BIGGER = 16;
  int IN = 17;
  int BETWEEN = 18;
  int LIKE = 19;
  int TRUE = 20;
  int FALSE = 21;
  int NULL = 22;
  int ESCAPE = 23;
  int BITAND = 24;
  int VALUE = 25;
  int STRING = 27;
  int SUPER = 29;
  int DOT = 30;
  int COMMA = 31;
  int FIELD = 32;
  int LETTER = 33;
  int NUM = 34;
  int SYMBOL = 35;
  int INTEGER = 36;
  int FLOAT = 37;
  int DECIMAL = 38;
  int PLUS = 39;
  int MINUS = 40;
  int MULT = 41;
  int DIV = 42;

  int DEFAULT = 0;
  int _STRING = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"NOT\"",
    "\"AND\"",
    "\"OR\"",
    "\"<=\"",
    "\">=\"",
    "<NOTEQUAL>",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"IN\"",
    "\"BETWEEN\"",
    "\"LIKE\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"NULL\"",
    "\"ESCAPE\"",
    "\"BITAND\"",
    "\"value\"",
    "\"\\\'\"",
    "<STRING>",
    "\"\\\'\"",
    "\"super.\"",
    "\".\"",
    "\",\"",
    "<FIELD>",
    "<LETTER>",
    "<NUM>",
    "<SYMBOL>",
    "<INTEGER>",
    "<FLOAT>",
    "<DECIMAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
